server:
  port: 8080

spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 98.7%root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    # 主Redis
    main: 
      hostName: 192.168.100.15
      port: 6379
    # 备份Redis
    bak: 
      hostName: localhost
      port: 6379
   ###ThymeLeaf配置 
  thymeleaf:
   #模板的模式，支持 HTML, XML TEXT JAVASCRIPT 
    mode: HTML5 
    #编码 可不用配置 
    encoding: UTF-8 
    #内容类别,可不用配置 
    content-type: text/html 
    #开发配置为false,避免修改模板还要重启服务器 
    cache: false 

