
spring:
  rabbitmq:
    host: rabbitmq.study.com
    port: 5672
    username: admin
    password: admin  
   # listener:
   #   simple:
   #      prefetch: 1
   
# 连接、通道缓存配置，高并发访问MQ时才需要配置。  
    cache:
      channel:
        checkout-timeout: 0 #如果已达到缓存大小，则等待获取通道的时间。如果为0，则始终创建一个新通道。
        size: 100   #要保留在缓存中的通道数。当checkout-timeout>为0时，表示每个连接的最大通道数。
     # connection:
        #mode: connection  #连接工厂缓存模式 ,默认是 channel
        #size: 10    #缓存的连接数量，仅在mode 为 connection时有效
    

    publisher-returns:  true   #开启spring中的消息退回发布者支持
    publisher-confirms: true   #开启spring中的发布者消息确认支持
    template:
      mandatory: true   # 全局默认设置为：消息不可路由强制退回   这个基本没什么用处，因为还需要为RabbitTemplate设置退回回调才行（可以在那里一并设置）     
    
    
   # listener:
    #  simple:     
    #    acknowledge-mode: manual
    #    prefetch: 1
      
    #  direct:
    #    acknowledge-mode: manual
    #     prefetch: 1
    
    
